### ISSUE TITLE
Keypad does not seem to be working on Windows 10

### ISSUE THREAD

**Issue by risingfish** [dungeons-of-moria/umoria#35]
The keypad doesn't appear to be working correctly in Windows 10 (version 2004).

With Num Lock on every key opens the Repeat dialog with the corresponding number.  With Num Lock off the keypad buttons do various things like browse books, run in a direction, open the mini-map, etc.

**Comment by mrcook** [comment]
Thanks for submitting this issue @risingfish , I'll take a look as soon as I am able.

**Comment by risingfish** [comment]
Awesome, thank you! I've been poking around in the source code, but I've
never used C so I'm of limited help here. :(

**Comment by BacchusPlateau** [comment]
I'm having a devil of a time getting it to compile.  Downloaded and installed all of the mwing support via pacman but i'm stuck on:

CMake Error at C:/dox/code/mysys64/mingw64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY)
Call Stack (most recent call first):
  C:/dox/code/mysys64/mingw64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/dox/code/mysys64/mingw64/share/cmake-3.18/Modules/FindCurses.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:267 (find_package)

Anyone have any ideas?  I've googled and gone through everything on StackOverflow but no joy.  :-(         I was interested in running this locally after seeing this game mentioned on a YouTube video.

**Comment by BacchusPlateau** [comment]
Fixed it.  I had to add these lines to the file "FindCurses.cmake"

set( CURSES_LIBRARY "/usr/lib/libncurses.a")
set( CURSES_INCLUDE_DIR "/usr/include")

**Comment by mrcook** [comment]
Hi @risingfish and @BacchusPlateau , please accept my apologies for not getting back to this. Basically, life happened, so I've not had a proper chance to take a look.

Once things settle down I'll get on it.

**Comment by mrcook** [comment]
@risingfish my apologies for the delay in getting back to you. I tested this with [v5.7.13](https://github.com/dungeons-of-moria/umoria/releases/tag/v5.7.13) and everything worked fine. With the numlock enabled I was able to walk around no problem.

Please try again with that version and let me know how you get on.

**Comment by risingfish** [comment]
Thanks for taking a look @mrcook  . I just tried it again and I'm still not able to move. The same as I described above. I might take another swing at getting it to compile myself and maybe try to debug.

**Comment by mrcook** [comment]
Hi @risingfish, I'm going to close this issue as I've not been able to replicate the problem. If you find where the problem is, please feel free to re-open.

Thanks!
Michael
